import RPi.GPIO as GPIO

# VARIABLES PIN LED RGB
BLUEPIN = 25
GREENPIN = 15
REDPIN = 18

GPIO.setmode(GPIO.BCM)
GPIO.setup(BLUEPIN, GPIO.OUT)  # BLUE
GPIO.setup(GREENPIN, GPIO.OUT)  # GREEN
GPIO.setup(REDPIN, GPIO.OUT)  # RED
GPIO.setwarnings(False)